### ISSUE TITLE
[RFC] calendar_fieldservice

### ISSUE THREAD

**Issue by osi-scampbell** [OCA/calendar#17]
**Calendar Field Service**
Repository: OCA/calendar

Module name: calendar_fieldservice

Dependency: ['calendar_timeline', 'fieldservice']

License: AGPL-3

**Module description**
"This Module creates corresponding Calendar Events for FSM Orders, the two objects are synchronized so any changes made ton/a the FSM Order should be reflected in the Calendar Event"

**Usage**

- Create an FSM Order
- Verify that a Calendar Event has been created
- Edit the FSM Order Starting Date or Estimated Duration
- Verify the Calendar Event reflects the changes made on the FSM Order
- Delete the FSM Order, verify the Calendar Event has also been deleted

**Test Scenarios**
Scenario 1:

- Create an FSM Order
- Verify Calendar Event has been created
- Delete the FSM Order
- Verify Calendar Event has been deleted

Scenario 2:

- Create an FSM Order
- Verify Calendar Event has been created
- Change any of the following fields (schedule_date_start, duration, user_id, person_id)
- Verify the change has been made on the Calendar Event

Scenario 3:

- Create an FSM Order
- Verify Calendar Event has been created
- Change any of the following fields (date_start, planned_hours, user_id, manager_id)
- Verify the change has been made on the FSM Order

As stated in my previous Issue, I think we can build off of or add this to this PR #12 the modules here are very good, the purpose of this issue is to synchronize a calendar event with an fsm.order

**Comment by bodedra** [comment]
@osi-scampbell This should move in OCA/field-service repository.
