### ISSUE TITLE
Odoo Server Error - Validation Error

### ISSUE THREAD

**Issue by kelvingarger** [OCA/calendar#50]
Verrsion 12 Enterprise on Odoo.sh
 
I keep getting this validation error in any Schedule try 

Cannot schedule these bookings because they do not fit in their type or resources calendars, or because all resources are busy:

<img width="954" alt="Validation Error2" src="https://user-images.githubusercontent.com/35907806/137626546-b66b21cc-4d58-46b5-942d-a1fab0be1e8d.PNG">

What is the meaning of fit in their type? also, neitther the user or the resources are busy

**Comment by pedrobaeza** [comment]
It means it doesn't fit in the corresponding calendar. I see too much hours there.

Closing as no issue, but misuse of the module.

**Comment by kelvingarger** [comment]
misuse of the module? There is no clear step by step guide..

am just trying to show you that am not able to schedule a thing.

Chechk this video with my last try:

https://www.dropbox.com/s/k8ww4xq2ugoidhk/screen-capture%20%281%29.webm?dl=0 

and let me know if am wrong or not.

**Comment by kelvingarger** [comment]
Hola Pedro, ¿cómo estás?

Quisiera me ayudaras a comprender porque asumes que he hecho mal uso del
módulo, No hay una guía clara paso a paso.

Solo estoy tratando de mostrarte que no puedo programar nada.

Mira este video con mi último intento:

https://www.dropbox.com/s/k8ww4xq2ugoidhk/screen-capture%20%281%29.webm?dl=0

Si me pudieras ayudar te estaría enormemente agradecido.

Saludos,

*Kelvin Garcia G*
IT Solutions Specialist
*Whatsapp:  849-246-3683*
*Directo:       809-257-1134*
*SOPORTE TECNICO | PROYECTOS DE TECNOLOGIA EN GENERAL*
*Consultoria IT **|** Microsoft | VMware **|** Veeam Backup **|** HPE Aruba
Networking **|** Project Managment **|*

**Comment by pedrobaeza** [comment]
The hours you are scheduling are outside of the "Standard 40 works / week" calendar.

**Comment by kelvingarger** [comment]
Ok, thanks for the clarification.

I found the calendar was missing the start and the end date:

[image: image.png]
*Kelvin Garcia G*
IT Solutions Specialist
*Whatsapp:  849-246-3683*
*Directo:       809-257-1134*
*SOPORTE TECNICO | PROYECTOS DE TECNOLOGIA EN GENERAL*
*Consultoria IT **|** Microsoft | VMware **|** Veeam Backup **|** HPE Aruba
Networking **|** Project Managment **|*
