### ISSUE TITLE
Resource booking - access error for confirmed bookings [v12]

### ISSUE THREAD

**Issue by marcinkuk** [OCA/calendar#74]
## Module
resource_booking

## Describe the bug
Resource Booking / Manager and User can't open and view bookings confirmed via portal user.

```
Odoo server error [access error]
The requested operation cannot be completed due to security restrictions.
Please contact your system administrator.
(Document type: Event, Operation: read) - (Records: [1238], User: 7)

```
## To Reproduce
**Affected versions**:
Odoo 12.0-20211006 (Community Edition)
resource_booking: 12.0.1.5.1

1. Create human resource with any working times
2. Create Combination (use human resource created above)
3. Create Types (use combination used above)
4. Create Booking (from list view)
- set Requester (random contact)
- set Type (use created above)
- Save
5. Share booking - Send email
6. Schedule and confirm booking by portal user (use link in email)
7. Open booking from Resource Booking - Odoo server error [access error] occurs

**Expected behavior**
Can open and view confirmed booking.

**Additional context**
Tried in several environements with different odoo v12 builds.

**Comment by casterock** [comment]
How did you solve this? I have same problem on Odoo 13

**Comment by marcinkuk** [comment]
> How did you solve this? I have same problem on Odoo 13

Didn't solve it. I'm stuck without a solution.
