### ISSUE TITLE
Calendar Partner Color error

### ISSUE THREAD

**Issue by Taspidis** [OCA/calendar#94]
I get this error when i'm trying to install this module on odoo15.

Element '<field name="user_ids">' cannot be located in parent view

View error context:
{'file': '/home/giorgos/odoo15/custom/calendar_partner_color/views/calendar_event.xml',
 'line': 2,
 'name': 'calendar.event',
 'view': ir.ui.view(1368,),
 'view.model': 'calendar.event',
 'view.parent': ir.ui.view(1276,),
 'xmlid': 'view_calendar_event_calendar'}

**Comment by pedrobaeza** [comment]
That's normal, as the module is not migrated to that version, but for 14.0.

**Comment by Taspidis** [comment]
Thank you for the response! But it can be migrated for version 15 right?

Στις Τρί 25 Απρ 2023, 21:45 ο χρήστης Pedro M. Baeza <
***@***.***> έγραψε:

**Comment by pedrobaeza** [comment]
Yes, you can fund anyone to do it or wait if someone does it voluntarily.
